version: "3.8"

services:
  backend:
    build: ./backend   # Build context is the backend folder
    ports:
      - "3000:3000"  # Map ports
    volumes:
      - ./:/app
      - /app/node_modules  # Mount the node_modules folder to persist across builds
