services:
  nodejs:
    container_name: nodejs-container
    # You can choose between two methods for setting up the Node.js backend:
    # 1. Build locally: If you want to build the backend from your local source, 
    #    use the 'build: ./backend' option. 
    #    - Ensure you cd and have run `npm i` inside the backend folder before building then go back to the root folder.
    # 2. Pull from repository: Alternatively, use the pre-built image from Docker Hub
    #    by specifying the 'image' option (as shown below) to pull the image directly.
    #    - This method avoids building locally and pulls the image from a remote repo.
    # Uncomment one of the following options based on your needs:
    # build: ./backend # Build locally
    image: jasonerasmus264/hms_app_marvellous_machines-nodejs:main  # Pull the image from Docker Hub
    ports:
      - "3000:3000"                        # Expose port 3000 for the Node.js backend
    expose:
      - 3000
    volumes:
      - ./backend:/app                     # Mount backend folder to /app inside the container
    environment:
      MYSQL_HOST: mysql                      # Connect to MySQL running on the mysql service
      MYSQL_DATABASE: nwu_hms               # Initial database to create
      MYSQL_USER: admin                     # MySQL username
      MYSQL_PASSWORD: 'hms'                   # Set MySQL admin password
      MYSQL_PORT: 3306
    networks:
      - internalnet
    depends_on:
      - mysql                              # Wait for MySQL to be up before starting the backend

  mysql:
    container_name: mysql-container
    image: mysql:8.0.39                     # Use the 8.0.39 MySQL image
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - dev-mysql:/var/lib/mysql            # Persist MySQL data in the named volume
      - ./dump:/docker-entrypoint-initdb.d  # Mount the dump folder for initialization
    ports:
      - "3307:3306"                         # Expose MySQL on port 3306
    expose:
      - 3306
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: nwu_hms               # Initial database to create
      MYSQL_USER: admin                     # MySQL username
      MYSQL_PASSWORD: 'hms'                   # Set MySQL admin password
      MYSQL_ROOT_PASSWORD: 'hms'             # Set MySQL root password
    networks:
      - internalnet

networks:
  internalnet:                              # Define a bridge network for inter-container communication
    driver: bridge                          # Use the bridge driver for network isolation

volumes:
  dev-mysql:                                # Named volume for MySQL persistence